version: '3'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3091:3091"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
      - DUCOR_EOS_RETHINKHOST=localhost
      - DUCOR_ETH_PROVIDER=ws://localhost:8545
      - DUCOR_API_PORT=3091
    restart: on-failure

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - DUCOR_API_URL=${BACKEND_IP_OR_DNS}
        - DUCOR_API_PORT=3091
    ports:
      - "3090:80"
    depends_on:
      - backend
