version: '3'

services:
  backend:
    environment:
      - NODE_ENV=production
      - DUCOR_EOS_RETHINKHOST=${RETHINKDB_PROD_IP_OR_DNS}
      - DUCOR_ETH_PROVIDER=ws://${ETH_PROVIDER_PROD_IP_OR_DNS}:8545
      - DUCOR_EOS_ENDPOINT=${DUCOR_EOS_ENDPOINT}
      - DUCOR_EOS_CHAINID=${DUCOR_EOS_CHAINID}
      - DUCOR_EOS_WATCH_DELAY=${DUCOR_EOS_WATCH_DELAY}
    network_mode: host

  frontend:
    build:
      args:
        - DUCOR_API_URL=${BACKEND_PROD_IP_OR_DNS}
