version: '3'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3091:3091"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=production
      - DUCOR_API_PORT=3091
      - DUCOR_EOS_RETHINKHOST=${DUCOR_EOS_RETHINKHOST}
      - DUCOR_ETH_MASTER_ADDRESS=${DUCOR_ETH_MASTER_ADDRESS}
      - DUCOR_ETH_ORACLE_ACCOUNT=${DUCOR_ETH_ORACLE_ACCOUNT}
      - DUCOR_ETH_ORACLE_PRIVATEKEY=${DUCOR_ETH_ORACLE_PRIVATEKEY}
      - DUCOR_ETH_PROVIDER=${DUCOR_ETH_PROVIDER}
      - DUCOR_ETH_FROM_BLOCK=${DUCOR_ETH_FROM_BLOCK}
      - DUCOR_EOS_ENDPOINT=${DUCOR_EOS_ENDPOINT}
      - DUCOR_EOS_CHAINID=${DUCOR_EOS_CHAINID}
      - DUCOR_EOS_WATCH_DELAY=${DUCOR_EOS_WATCH_DELAY}
      - DUCOR_EOS_ORACLE_PRIVATEKEY=${DUCOR_EOS_ORACLE_PRIVATEKEY}
      - DUCOR_EOS_ORACLE_ACCOUNT=${DUCOR_EOS_ORACLE_ACCOUNT}
      - DUCOR_EOS_MASTER_ORACLE=${DUCOR_EOS_MASTER_ORACLE}
      - LOG_LEVEL=${LOG_LEVEL}
    network_mode: host
    restart: on-failure

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - DUCOR_API_URL=${DUCOR_API_URL}
        - DUCOR_API_PORT=3091
    ports:
      - "3090:80"
    depends_on:
      - backend
